### ISSUE TITLE
Doubled order line quantity

### ISSUE THREAD

**Issue by forsvunnet** [krokedil/woocommerce-gateway-klarna#40]
### Expected behavior

Order line should contain the same quantity as the customer orders

### Actual behavior

In some edge cases the order quantity is doubled

WooCommerce:
![screen shot 2017-02-02 at 4 46 30 pm](https://cloud.githubusercontent.com/assets/799281/22556375/35cc3d78-e967-11e6-9568-f3e0f09e34a4.png)

Klarna:
![screen shot 2017-02-02 at 4 47 23 pm](https://cloud.githubusercontent.com/assets/799281/22556399/4e25e180-e967-11e6-8530-9d9ce5ad1904.png)

Notice that the quantity is not the same.

### Steps to reproduce the behavior

Unknown. This is possibly linked to a previous bug that caused duplicated order lines

### WordPress version

4.6.1

### WooCommerce version

2.6.8

### Klarna country

Norway

**Comment by slobodan** [comment]
@forsvunnet how frequent is this? And if you noticed, is there anything these orders have in common?

**Comment by WarrenMoore** [comment]
@slobodan we've had this happen to us once recently (Feb 28th), though we had them added as separately line items (with the same cart hash) which ends in the exact same effect. I've pasted logs from the order below, it appears `prepare_wc_order` was triggered twice following a guest checkout change of address for some reason (line no. 1970949):

```
1970753:02-28-2017 @ 13:18:58 - Local order created, order ID: 207615
1970754:02-28-2017 @ 13:18:58 - 0.01454600 1488287938: Current action for preparing order 207615: the_content
1970755:02-28-2017 @ 13:18:58 - 0.01481300 1488287938: Debug backtrace for preparing order 207615: #0 /home/hrl/public_html/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-checkout.php(1438): WC_Gateway_Klarna_K2WC->prepare_wc_order('guest_checkout@...')
1970769:02-28-2017 @ 13:18:58 - 0.01594600 1488287938: Removed order items from order 207615...
1970770:02-28-2017 @ 13:18:58 - 0.01672500 1488287938: Customer user agent for 207615: Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) GSA/23.0.147401934 Mobile/14D27 Safari/600.1.4
1970771:02-28-2017 @ 13:18:58 - 0.01739000 1488287938: Adding items to order 207615...
1970772:02-28-2017 @ 13:18:58 - 0.05264700 1488287938: Added item 313141 (cart item key: f9340873448ccb343fda29f3c8849cb3) to order 207615...
1970773:02-28-2017 @ 13:18:58 - 0.05636800 1488287938: Finished adding items to order 207615...
1970774:02-28-2017 @ 13:18:58 - 0.05704200 1488287938: Adding fees to order 207615...
1970775:02-28-2017 @ 13:18:58 - 0.05719200 1488287938: Finished adding fees to order 207615...
1970776:02-28-2017 @ 13:18:58 - 0.05777000 1488287938: Adding shipping to order 207615...
1970777:02-28-2017 @ 13:18:58 - 0.08856300 1488287938: Added shipping 313142 (package key: 0) to order 207615...
1970778:02-28-2017 @ 13:18:58 - 0.08884300 1488287938: Finished adding shipping to order 207615...
1970779:02-28-2017 @ 13:18:58 - 0.08953800 1488287938: Adding tax rows to order 207615...
1970780:02-28-2017 @ 13:18:58 - 0.10176300 1488287938: Added tax rate 28 to order 207615...
1970781:02-28-2017 @ 13:18:58 - 0.10204200 1488287938: Finished adding tax rows to order 207615...
1970782:02-28-2017 @ 13:18:58 - 0.10275400 1488287938: Adding coupons to order 207615...
1970783:02-28-2017 @ 13:18:58 - 0.10293700 1488287938: Finished adding coupons to order 207615...
1970785:02-28-2017 @ 13:18:58 - 0.11136100 1488287938: Setting order totals for order 207615...
1970786:02-28-2017 @ 13:24:21 - 0.70151700 1488288261: Current action for preparing order 207615: wp_ajax_nopriv_kco_iframe_shipping_address_change_cb
1970787:02-28-2017 @ 13:24:21 - 0.70248200 1488288261: Debug backtrace for preparing order 207615: #0 /home/hrl/public_html/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-checkout.php(1438): WC_Gateway_Klarna_K2WC->prepare_wc_order('guest_checkout@...')
1970792:02-28-2017 @ 13:24:21 - 0.83437300 1488288261: Removed order items from order 207615...
1970793:02-28-2017 @ 13:24:21 - 0.83492100 1488288261: Customer user agent for 207615: Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) GSA/23.0.147401934 Mobile/14D27 Safari/600.1.4
1970794:02-28-2017 @ 13:24:21 - 0.83598300 1488288261: Adding items to order 207615...
1970795:02-28-2017 @ 13:24:22 - 0.09660400 1488288262: Added item 313148 (cart item key: f9340873448ccb343fda29f3c8849cb3) to order 207615...
1970796:02-28-2017 @ 13:24:22 - 0.10402900 1488288262: Finished adding items to order 207615...
1970797:02-28-2017 @ 13:24:22 - 0.10507300 1488288262: Adding fees to order 207615...
1970798:02-28-2017 @ 13:24:22 - 0.10528400 1488288262: Finished adding fees to order 207615...
1970799:02-28-2017 @ 13:24:22 - 0.10580700 1488288262: Adding shipping to order 207615...
1970800:02-28-2017 @ 13:24:22 - 0.27796700 1488288262: Added shipping 313149 (package key: 0) to order 207615...
1970801:02-28-2017 @ 13:24:22 - 0.27842900 1488288262: Finished adding shipping to order 207615...
1970802:02-28-2017 @ 13:24:22 - 0.27971500 1488288262: Adding tax rows to order 207615...
1970803:02-28-2017 @ 13:24:22 - 0.88843600 1488288262: Added tax rate 28 to order 207615...
1970804:02-28-2017 @ 13:24:22 - 0.88874300 1488288262: Finished adding tax rows to order 207615...
1970805:02-28-2017 @ 13:24:22 - 0.90625500 1488288262: Adding coupons to order 207615...
1970806:02-28-2017 @ 13:24:22 - 0.90662700 1488288262: Finished adding coupons to order 207615...
1970808:02-28-2017 @ 13:24:22 - 0.99022300 1488288262: Setting order totals for order 207615...
1970811:02-28-2017 @ 13:24:33 - 0.90053400 1488288273: Current action for preparing order 207615: the_content
1970812:02-28-2017 @ 13:24:33 - 0.90119100 1488288273: Debug backtrace for preparing order 207615: #0 /home/hrl/public_html/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-checkout.php(1438): WC_Gateway_Klarna_K2WC->prepare_wc_order('guest_checkout@...')
1970826:02-28-2017 @ 13:24:33 - 0.93629600 1488288273: Removed order items from order 207615...
1970827:02-28-2017 @ 13:24:33 - 0.93675300 1488288273: Customer user agent for 207615: Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) GSA/23.0.147401934 Mobile/14D27 Safari/600.1.4
1970828:02-28-2017 @ 13:24:33 - 0.93773900 1488288273: Adding items to order 207615...
1970829:02-28-2017 @ 13:24:34 - 0.00376600 1488288274: Added item 313152 (cart item key: f9340873448ccb343fda29f3c8849cb3) to order 207615...
1970830:02-28-2017 @ 13:24:34 - 0.01818900 1488288274: Finished adding items to order 207615...
1970831:02-28-2017 @ 13:24:34 - 0.01959000 1488288274: Adding fees to order 207615...
1970832:02-28-2017 @ 13:24:34 - 0.01990300 1488288274: Finished adding fees to order 207615...
1970833:02-28-2017 @ 13:24:34 - 0.02072100 1488288274: Adding shipping to order 207615...
1970834:02-28-2017 @ 13:24:34 - 0.27926800 1488288274: Added shipping 313153 (package key: 0) to order 207615...
1970835:02-28-2017 @ 13:24:34 - 0.27976400 1488288274: Finished adding shipping to order 207615...
1970836:02-28-2017 @ 13:24:34 - 0.28127000 1488288274: Adding tax rows to order 207615...
1970837:02-28-2017 @ 13:24:34 - 0.37730500 1488288274: Added tax rate 28 to order 207615...
1970838:02-28-2017 @ 13:24:34 - 0.37937800 1488288274: Finished adding tax rows to order 207615...
1970839:02-28-2017 @ 13:24:34 - 0.38421200 1488288274: Adding coupons to order 207615...
1970840:02-28-2017 @ 13:24:34 - 0.38668100 1488288274: Finished adding coupons to order 207615...
1970842:02-28-2017 @ 13:24:34 - 0.41869100 1488288274: Setting order totals for order 207615...
1970881:02-28-2017 @ 13:25:03 - 0.82547000 1488288303: Current action for preparing order 207615: the_content
1970882:02-28-2017 @ 13:25:03 - 0.82594900 1488288303: Debug backtrace for preparing order 207615: #0 /home/hrl/public_html/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-checkout.php(1438): WC_Gateway_Klarna_K2WC->prepare_wc_order('guest_checkout@...')
1970896:02-28-2017 @ 13:25:03 - 0.83754400 1488288303: Removed order items from order 207615...
1970897:02-28-2017 @ 13:25:03 - 0.83808400 1488288303: Customer user agent for 207615: Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) GSA/23.0.147401934 Mobile/14D27 Safari/600.1.4
1970898:02-28-2017 @ 13:25:03 - 0.83913000 1488288303: Adding items to order 207615...
1970899:02-28-2017 @ 13:25:03 - 0.90955300 1488288303: Added item 313162 (cart item key: f9340873448ccb343fda29f3c8849cb3) to order 207615...
1970900:02-28-2017 @ 13:25:03 - 0.91347100 1488288303: Finished adding items to order 207615...
1970901:02-28-2017 @ 13:25:03 - 0.91456100 1488288303: Adding fees to order 207615...
1970902:02-28-2017 @ 13:25:03 - 0.91478000 1488288303: Finished adding fees to order 207615...
1970903:02-28-2017 @ 13:25:03 - 0.91546900 1488288303: Adding shipping to order 207615...
1970904:02-28-2017 @ 13:25:03 - 0.99159000 1488288303: Added shipping 313163 (package key: 0) to order 207615...
1970905:02-28-2017 @ 13:25:03 - 0.99204300 1488288303: Finished adding shipping to order 207615...
1970906:02-28-2017 @ 13:25:03 - 0.99331200 1488288303: Adding tax rows to order 207615...
1970907:02-28-2017 @ 13:25:04 - 0.00892000 1488288304: Added tax rate 28 to order 207615...
1970908:02-28-2017 @ 13:25:04 - 0.00927300 1488288304: Finished adding tax rows to order 207615...
1970909:02-28-2017 @ 13:25:04 - 0.01025500 1488288304: Adding coupons to order 207615...
1970910:02-28-2017 @ 13:25:04 - 0.01050100 1488288304: Finished adding coupons to order 207615...
1970912:02-28-2017 @ 13:25:04 - 0.01220100 1488288304: Setting order totals for order 207615...
1970915:02-28-2017 @ 13:25:42 - 0.61781800 1488288342: Current action for preparing order 207615: the_content
1970916:02-28-2017 @ 13:25:42 - 0.61834700 1488288342: Debug backtrace for preparing order 207615: #0 /home/hrl/public_html/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-checkout.php(1438): WC_Gateway_Klarna_K2WC->prepare_wc_order('guest_checkout@...')
1970930:02-28-2017 @ 13:25:42 - 0.65915000 1488288342: Removed order items from order 207615...
1970931:02-28-2017 @ 13:25:42 - 0.65966800 1488288342: Customer user agent for 207615: Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) GSA/23.0.147401934 Mobile/14D27 Safari/600.1.4
1970932:02-28-2017 @ 13:25:42 - 0.66071400 1488288342: Adding items to order 207615...
1970933:02-28-2017 @ 13:25:42 - 0.72419000 1488288342: Added item 313166 (cart item key: f9340873448ccb343fda29f3c8849cb3) to order 207615...
1970934:02-28-2017 @ 13:25:42 - 0.72809600 1488288342: Finished adding items to order 207615...
1970935:02-28-2017 @ 13:25:42 - 0.72933900 1488288342: Adding fees to order 207615...
1970936:02-28-2017 @ 13:25:42 - 0.72957900 1488288342: Finished adding fees to order 207615...
1970937:02-28-2017 @ 13:25:42 - 0.73040700 1488288342: Adding shipping to order 207615...
1970938:02-28-2017 @ 13:25:42 - 0.80318700 1488288342: Added shipping 313167 (package key: 0) to order 207615...
1970939:02-28-2017 @ 13:25:42 - 0.80363500 1488288342: Finished adding shipping to order 207615...
1970940:02-28-2017 @ 13:25:42 - 0.80474500 1488288342: Adding tax rows to order 207615...
1970941:02-28-2017 @ 13:25:42 - 0.83477000 1488288342: Added tax rate 28 to order 207615...
1970942:02-28-2017 @ 13:25:42 - 0.83518600 1488288342: Finished adding tax rows to order 207615...
1970943:02-28-2017 @ 13:25:42 - 0.83610900 1488288342: Adding coupons to order 207615...
1970944:02-28-2017 @ 13:25:42 - 0.83637100 1488288342: Finished adding coupons to order 207615...
1970946:02-28-2017 @ 13:25:42 - 0.83818900 1488288342: Setting order totals for order 207615...
1970949:02-28-2017 @ 13:26:21 - 0.70443200 1488288381: Current action for preparing order 207615: wp_ajax_nopriv_kco_iframe_shipping_address_change_cb
1970950:02-28-2017 @ 13:26:21 - 0.70496600 1488288381: Debug backtrace for preparing order 207615: #0 /home/hrl/public_html/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-checkout.php(1438): WC_Gateway_Klarna_K2WC->prepare_wc_order('guest_checkout@...')
1970955:02-28-2017 @ 13:26:21 - 0.71810200 1488288381: Current action for preparing order 207615: the_content
1970956:02-28-2017 @ 13:26:21 - 0.71844700 1488288381: Debug backtrace for preparing order 207615: #0 /home/hrl/public_html/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-checkout.php(1438): WC_Gateway_Klarna_K2WC->prepare_wc_order('guest_checkout@...')
1970970:02-28-2017 @ 13:26:21 - 0.76008600 1488288381: Removed order items from order 207615...
1970971:02-28-2017 @ 13:26:21 - 0.76047700 1488288381: Customer user agent for 207615: Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) GSA/23.0.147401934 Mobile/14D27 Safari/600.1.4
1970972:02-28-2017 @ 13:26:21 - 0.78297300 1488288381: Removed order items from order 207615...
1970973:02-28-2017 @ 13:26:21 - 0.78342500 1488288381: Customer user agent for 207615: Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) GSA/23.0.147401934 Mobile/14D27 Safari/600.1.4
1970974:02-28-2017 @ 13:26:21 - 0.78380400 1488288381: Adding items to order 207615...
1970975:02-28-2017 @ 13:26:21 - 0.79636600 1488288381: Adding items to order 207615...
1970976:02-28-2017 @ 13:26:21 - 0.86093800 1488288381: Added item 313171 (cart item key: f9340873448ccb343fda29f3c8849cb3) to order 207615...
1970977:02-28-2017 @ 13:26:21 - 0.86452600 1488288381: Finished adding items to order 207615...
1970978:02-28-2017 @ 13:26:21 - 0.86548900 1488288381: Adding fees to order 207615...
1970979:02-28-2017 @ 13:26:21 - 0.86570800 1488288381: Finished adding fees to order 207615...
1970980:02-28-2017 @ 13:26:21 - 0.86654900 1488288381: Adding shipping to order 207615...
1970981:02-28-2017 @ 13:26:21 - 0.88807300 1488288381: Added item 313172 (cart item key: f9340873448ccb343fda29f3c8849cb3) to order 207615...
1970982:02-28-2017 @ 13:26:21 - 0.89876100 1488288381: Finished adding items to order 207615...
1970983:02-28-2017 @ 13:26:21 - 0.89945000 1488288381: Adding fees to order 207615...
1970984:02-28-2017 @ 13:26:21 - 0.89961300 1488288381: Finished adding fees to order 207615...
1970985:02-28-2017 @ 13:26:21 - 0.89990200 1488288381: Adding shipping to order 207615...
1970986:02-28-2017 @ 13:26:21 - 0.96265000 1488288381: Added shipping 313173 (package key: 0) to order 207615...
1970987:02-28-2017 @ 13:26:21 - 0.96294100 1488288381: Finished adding shipping to order 207615...
1970988:02-28-2017 @ 13:26:21 - 0.96356500 1488288381: Adding tax rows to order 207615...
1970991:02-28-2017 @ 13:26:22 - 0.04193500 1488288382: Added tax rate 28 to order 207615...
1970992:02-28-2017 @ 13:26:22 - 0.04230600 1488288382: Finished adding tax rows to order 207615...
1970993:02-28-2017 @ 13:26:22 - 0.04323800 1488288382: Adding coupons to order 207615...
1970994:02-28-2017 @ 13:26:22 - 0.04347500 1488288382: Finished adding coupons to order 207615...
1970996:02-28-2017 @ 13:26:22 - 0.05045500 1488288382: Added shipping 313175 (package key: 0) to order 207615...
1970997:02-28-2017 @ 13:26:22 - 0.05083600 1488288382: Finished adding shipping to order 207615...
1970998:02-28-2017 @ 13:26:22 - 0.10985700 1488288382: Adding coupons to order 207615...
1970999:02-28-2017 @ 13:26:22 - 0.11023100 1488288382: Finished adding coupons to order 207615...
1971001:02-28-2017 @ 13:26:22 - 0.11070500 1488288382: Setting order totals for order 207615...
1971002:02-28-2017 @ 13:26:22 - 0.13852200 1488288382: Setting order totals for order 207615...
1971048:02-28-2017 @ 13:29:43 - 0.67786000 1488288583: Adding addresses to order 207615...
1971144:02-28-2017 @ 13:31:33 - 0.90210600 1488288693: Adding addresses to order 207615...
```
This is in the UK if that's of any help.

**Comment by slobodan** [comment]
@WarrenMoore sorry about the delay in responding, can you tell me which version of our plugin this order was created with? Was it 2.3 or later, because this issue should be fixed in that one.

**Comment by WarrenMoore** [comment]
This was with 2.3 unfortunately @slobodan - we took the v2.3 tag from Github (as it hadn't been approved through to woocommerce.com yet) at the end of Feb.
